# Generated by Django 5.2.5 on 2025-08-23 15:20

import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('Веб-разработка', 'Веб-разработка'), ('Мобильные приложения', 'Мобильные приложения'), ('Дизайн', 'Дизайн'), ('Копирайтинг', 'Копирайтинг'), ('SEO и маркетинг', 'SEO и маркетинг'), ('Переводы', 'Переводы')], max_length=64, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Навыки')),
                ('budget_type', models.CharField(choices=[('fixed', 'Фиксированный'), ('range', 'Диапазон')], default='fixed', max_length=16, verbose_name='Тип бюджета')),
                ('budget_fixed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фиксированный бюджет (₽)')),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Бюджет от (₽)')),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Бюджет до (₽)')),
                ('deadline', models.CharField(blank=True, max_length=120, verbose_name='Срок выполнения (текст)')),
                ('deadline_type', models.CharField(choices=[('flexible', 'Гибкий'), ('strict', 'Строгий')], default='flexible', max_length=16, verbose_name='Тип дедлайна')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Местоположение')),
                ('remote', models.BooleanField(default=True, verbose_name='Удалённо')),
                ('urgent', models.BooleanField(default=False, verbose_name='Срочное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=jobs.models.job_attachment_path, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Файл задания',
                'verbose_name_plural': 'Файлы задания',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
