# Generated by Django 5.2.5 on 2025-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено в'),
        ),
        migrations.AddField(
            model_name='job',
            name='canceled_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
    ]
