# Generated by Django 5.2.5 on 2025-08-18 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +79991234567', max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7XXXXXXXXXX (10 цифр после +7).', regex='^\\+7\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('executor', 'Исполнитель'), ('customer', 'Заказчик')], default='executor', max_length=16),
        ),
    ]
