# Generated by Django 5.2.5 on 2025-08-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='users_user_email_ci_unique',
        ),
    ]
